-- ============================================
-- TASK 7 - DIMENSIONAL MODEL (DDL)
-- ============================================

CREATE SCHEMA IF NOT EXISTS BL_DM;

-- Sequences

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CUSTOMERS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PRODUCTS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_STORES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_EMPLOYEES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_TIME_DAY
START WITH 1
INCREMENT BY 1;

-- DIM_CUSTOMER

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMER
(
    CUSTOMER_SURR_ID BIGINT
		DEFAULT nextval('BL_DM.SEQ_DIM_CUSTOMERS')
		PRIMARY KEY
	CUSTOMER_SRC_ID      VARCHAR(50) NOT NULL,

	FIRST_NAME           VARCHAR(100) NOT NULL,
	LAST_NAME            VARCHAR(100) NOT NULL,
	GENDER               VARCHAR(20) NOT NULL,
	BIRTH_DATE           DATE NOT NULL,
	EMAIL                VARCHAR(255) NOT NULL,
	PHONE                VARCHAR(30) NOT NULL,

	COUNTRY_SRC_ID       BIGINT NOT NULL,
	COUNTRY              VARCHAR(100) NOT NULL,

	CITY_SRC_ID          BIGINT NOT NULL,
	CITY                 VARCHAR(100) NOT NULL,

	SOURCE_SYSTEM        VARCHAR(50) NOT NULL,
	SOURCE_ENTITY        VARCHAR(50) NOT NULL,

	INSERT_DT            DATE NOT NULL,
	UPDATE_DT            DATE NOT NULL
);

-- DIM_PRODUCTS_SCD

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PRODUCTS_SCD
(
    PRODUCT_SURR_ID BIGINT
		DEFAULT nextval('BL_DM.SEQ_DIM_PRODUCTS')
		PRIMARY KEY,
	PRODUCT_SRC_ID       VARCHAR(50) NOT NULL,

	PRODUCT_CODE         VARCHAR(50) NOT NULL,
	PRODUCT_NAME         VARCHAR(255) NOT NULL,
	BRAND                VARCHAR(100) NOT NULL,

	CATEGORY_SRC_ID      BIGINT NOT NULL,
	CATEGORY             VARCHAR(100) NOT NULL,

	SUBCATEGORY_SRC_ID   BIGINT NOT NULL,
	SUBCATEGORY          VARCHAR(100) NOT NULL,

	COLOR_SRC_ID         BIGINT NOT NULL,
	COLOR                VARCHAR(50) NOT NULL,

	SIZE                 VARCHAR(20) NOT NULL,

	UNIT_PRICE           DECIMAL(18,2),
	UNIT_COST            DECIMAL(18,2),

	SOURCE_SYSTEM        VARCHAR(50) NOT NULL,
	SOURCE_ENTITY        VARCHAR(50) NOT NULL,

	START_DT             DATE NOT NULL,
	END_DT               DATE NOT NULL,
	IS_ACTIVE            VARCHAR(1) NOT NULL,

	INSERT_DT            DATE NOT NULL
);

-- DIM_STORE

CREATE TABLE IF NOT EXISTS BL_DM.DIM_STORE
(
    STORE_SURR_ID BIGINT
		DEFAULT nextval('BL_DM.SEQ_DIM_STORES')
		PRIMARY KEY,
	STORE_SRC_ID         VARCHAR(50) NOT NULL,

	STORE_NAME           VARCHAR(150) NOT NULL,
	ADDRESS              VARCHAR(255) NOT NULL,

	CITY_SRC_ID          BIGINT NOT NULL,
	CITY                 VARCHAR(100) NOT NULL,

	COUNTRY_SRC_ID       BIGINT NOT NULL,
	COUNTRY              VARCHAR(100) NOT NULL,

	SOURCE_SYSTEM        VARCHAR(50) NOT NULL,
	SOURCE_ENTITY        VARCHAR(50) NOT NULL,

	INSERT_DT            DATE NOT NULL,
	UPDATE_DT            DATE NOT NULL
);

-- DIM_EMPLOYEE

CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEE
(
    EMPLOYEE_SURR_ID BIGINT
		DEFAULT nextval('BL_DM.SEQ_DIM_EMPLOYEES')
		PRIMARY KEY,
	EMPLOYEE_SRC_ID      VARCHAR(50) NOT NULL,

	FIRST_NAME           VARCHAR(100) NOT NULL,
	LAST_NAME            VARCHAR(100) NOT NULL,
	POSITION             VARCHAR(100) NOT NULL,

	STORE_SRC_ID         BIGINT NOT NULL,
	STORE_NAME           VARCHAR(150) NOT NULL,

	CITY_SRC_ID          BIGINT NOT NULL,
	CITY                 VARCHAR(100) NOT NULL,

	COUNTRY_SRC_ID       BIGINT NOT NULL,
	COUNTRY              VARCHAR(100) NOT NULL,

	SOURCE_SYSTEM        VARCHAR(50) NOT NULL,
	SOURCE_ENTITY        VARCHAR(50) NOT NULL,

	INSERT_DT            DATE NOT NULL,
	UPDATE_DT            DATE NOT NULL
);

-- DIM_TIME_DAY

CREATE TABLE IF NOT EXISTS BL_DM.DIM_TIME_DAY
(
    DATE_SURR_ID BIGINT
		DEFAULT nextval('BL_DM.SEQ_DIM_TIME_DAY')
		PRIMARY KEY,
	EVENT_DT             DATE NOT NULL,

	DAY                  SMALLINT NOT NULL,
	MONTH                SMALLINT NOT NULL,
	MONTH_NAME           VARCHAR(20) NOT NULL,
	QUARTER              SMALLINT NOT NULL,
	YEAR                 SMALLINT NOT NULL,
	DAY_OF_WEEK          SMALLINT NOT NULL,
	WEEKEND_FLAG         CHAR(1) NOT NULL
);

-- FCT_SALES_DD

CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd
(
    customer_surr_id     BIGINT NOT NULL,
    product_surr_id      BIGINT NOT NULL,
    store_surr_id        BIGINT NOT NULL,
    employee_surr_id     BIGINT NOT NULL,
    date_surr_id         BIGINT NOT NULL,

    event_dt             DATE NOT NULL,

    quantity             INTEGER,
    unit_price           NUMERIC,
    unit_cost            NUMERIC,
    sales_amount         NUMERIC,
    cost_amount          NUMERIC,
    discount_amount      NUMERIC,
    payment_method       VARCHAR(50),
    channel              VARCHAR(20),
    profit_amount        NUMERIC,

    insert_dt            DATE,
    update_dt            DATE,

    CONSTRAINT fk_fct_customer
        FOREIGN KEY (customer_surr_id)
        REFERENCES bl_dm.dim_customer(customer_surr_id),

    CONSTRAINT fk_fct_product
        FOREIGN KEY (product_surr_id)
        REFERENCES bl_dm.dim_products_scd(product_surr_id),

    CONSTRAINT fk_fct_store
        FOREIGN KEY (store_surr_id)
        REFERENCES bl_dm.dim_store(store_surr_id),

    CONSTRAINT fk_fct_employee
        FOREIGN KEY (employee_surr_id)
        REFERENCES bl_dm.dim_employee(employee_surr_id),

    CONSTRAINT fk_fct_date
        FOREIGN KEY (date_surr_id)
        REFERENCES bl_dm.dim_time_day(date_surr_id)

)
PARTITION BY RANGE (event_dt);

CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_dd_default
PARTITION OF bl_dm.fct_sales_dd
DEFAULT;

CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_2025_10
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');

CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_2025_11
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');

CREATE TABLE IF NOT EXISTS bl_dm.fct_sales_2025_12
PARTITION OF bl_dm.fct_sales_dd
FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

-- ETL

-- DEFAULT ROW - DIM_CUSTOMER

INSERT INTO BL_DM.DIM_CUSTOMER
(
    CUSTOMER_SURR_ID,
    CUSTOMER_SRC_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    BIRTH_DATE,
    EMAIL,
    PHONE,
    COUNTRY_SRC_ID,
    COUNTRY,
    CITY_SRC_ID,
    CITY,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    INSERT_DT,
    UPDATE_DT
)
SELECT
    -1,
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    DATE '1900-01-01',
    'n.a.',
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    'MANUAL',
    'MANUAL',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS
(
    SELECT 1
    FROM BL_DM.DIM_CUSTOMER
    WHERE CUSTOMER_SURR_ID = -1
);

-- DEFAULT ROW - DIM_PRODUCTS_SCD

INSERT INTO BL_DM.DIM_PRODUCTS_SCD
(
    PRODUCT_SURR_ID,
    PRODUCT_SRC_ID,
    PRODUCT_CODE,
    PRODUCT_NAME,
    BRAND,
    CATEGORY_SRC_ID,
    CATEGORY,
    SUBCATEGORY_SRC_ID,
    SUBCATEGORY,
    COLOR_SRC_ID,
    COLOR,
    SIZE,
    UNIT_PRICE,
    UNIT_COST,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    START_DT,
    END_DT,
    IS_ACTIVE,
    INSERT_DT
)
SELECT
    -1,
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    'n.a.',
    0,
    0,
    'MANUAL',
    'MANUAL',
    CURRENT_DATE,
    DATE '9999-12-31',
    'Y',
    CURRENT_DATE
WHERE NOT EXISTS
(
    SELECT 1
    FROM BL_DM.DIM_PRODUCTS_SCD
    WHERE PRODUCT_SURR_ID = -1
);

-- DEFAULT ROW - DIM_STORE

INSERT INTO BL_DM.DIM_STORE
(
    STORE_SURR_ID,
    STORE_SRC_ID,
    STORE_NAME,
    ADDRESS,
    CITY_SRC_ID,
    CITY,
    COUNTRY_SRC_ID,
    COUNTRY,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    INSERT_DT,
    UPDATE_DT
)
SELECT
    -1,
    -1,
    'n.a.',
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    'MANUAL',
    'MANUAL',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS
(
    SELECT 1
    FROM BL_DM.DIM_STORE
    WHERE STORE_SURR_ID = -1
);

-- DEFAULT ROW - DIM_EMPLOYEE

INSERT INTO BL_DM.DIM_EMPLOYEE
(
    EMPLOYEE_SURR_ID,
    EMPLOYEE_SRC_ID,
    FIRST_NAME,
    LAST_NAME,
    POSITION,
    STORE_SRC_ID,
    STORE_NAME,
    CITY_SRC_ID,
    CITY,
    COUNTRY_SRC_ID,
    COUNTRY,
    SOURCE_SYSTEM,
    SOURCE_ENTITY,
    INSERT_DT,
    UPDATE_DT
)
SELECT
    -1,
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    -1,
    'n.a.',
    'MANUAL',
    'MANUAL',
    CURRENT_DATE,
    CURRENT_DATE
WHERE NOT EXISTS
(
    SELECT 1
    FROM BL_DM.DIM_EMPLOYEE
    WHERE EMPLOYEE_SURR_ID = -1
);

-- DEFAULT ROW - DIM_TIME_DAY

INSERT INTO BL_DM.DIM_TIME_DAY
(
    DATE_SURR_ID,
    EVENT_DT,
    DAY,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR,
    DAY_OF_WEEK,
    WEEKEND_FLAG
)
SELECT
    -1,
    DATE '1900-01-01',
    0,
    0,
    'n.a.',
    0,
    0,
    0,
    'Y'
WHERE NOT EXISTS
(
    SELECT 1
    FROM BL_DM.DIM_TIME_DAY
    WHERE DATE_SURR_ID = -1
);

COMMIT;

